name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          lune run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: zucchini.rbxm

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Move Build
        run: mv build/zucchini.rbxm zucchini.rbxm

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Zucchini ${{ github.ref_name }}
          files: |
            zucchini.rbxm

  publish:
    name: Publish
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wally Login
        run: wally login --token ${{ secrets.WALLY_AUTH_TOKEN }}

      - name: Wally Publish
        run: wally publish

      - name: Create Pesde Config Folder
        run: mkdir ~/.pesde

      - name: Pesde Login
        run: pesde auth login --token "${{ secrets.PESDE_AUTH_TOKEN }}"

      - name: Pesde Publish
        run: pesde publish -y
